version: "3.9"

services:
    app:
        container_name: vidaccess
        image: streamaccessspa
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
          - "8081:8080"