version: "3.9"


services:
    app:
        container_name: streamaccess-spa
        image: streamaccess-spa
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env    
        environment:
            - SA_API_URL=${SA_API_URL}
            - SRS_API_URL=${SRS_API_URL}
            - FF_API_HOST=${FF_API_HOST}
            - FF_API_PORT=${FF_API_PORT}
            - SRS_PUBLISH_URL=${SRS_PUBLISH_URL}
        restart: always
        ports:
          - "8081:80"