export const SET_CURRENT_STREAM = 'SET_CURRENT_STREAM';
export const UNSET_CURRENT_STREAM = 'UNSET_CURRENT_STREAM';
export const SET_STREAMS = 'SET_STREAMS';
export const LOADING_STREAMS = 'LOADING_STREAMS';
export const ERROR_LOADING_STREAMS = 'ERROR_LOADING_STREAMS';